### ISSUE TITLE
Crashes on IRI Version 1.4.1.2

### ISSUE THREAD

**Issue by danielfaust** [bluedigits/nstats#3]
```
12/17 17:56:00.100 [Thread-4] INFO  com.iota.iri.IXI - Starting script: ixi/nstats/index.js
Exception in thread "Thread-4" java.lang.NullPointerException
        at com.iota.iri.IXI.attach(IXI.java:249)
        at com.iota.iri.IXI.loadModule(IXI.java:223)
        at com.iota.iri.IXI.handlePathEvent(IXI.java:141)
        at com.iota.iri.IXI.handleModulePathEvent(IXI.java:123)
        at com.iota.iri.IXI.lambda$processWatchEvents$0(IXI.java:100)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.iota.iri.IXI.processWatchEvents(IXI.java:95)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by bluedigits** [comment]
I'm gonna investigate this problem, but seems to be IRI-related.
See https://github.com/iotaledger/iri/issues/426

**Comment by danielfaust** [comment]
Possibly a Docker Alpine issue. Had feedback in Slack that it does work.

**Comment by bluedigits** [comment]
Yep, you're right. As you can see here: https://github.com/anapsix/docker-alpine-java/issues/36
I'll roll back to openjdk:8-slim as long as we don't have any better option.

**Comment by bluedigits** [comment]
Thanks for the hint @danielfaust !

**Comment by bluedigits** [comment]
I'm going to close this since the docker images is based on an OpenJDK image which supports Nashorn.
